# Generated by Django 3.0.3 on 2020-09-09 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20200909_2252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='slugz',
            new_name='slug',
        ),
    ]
